site:
  baseline: Common Cents Distributors
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: A review blog for popular Amazon products
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Amazon Product Review
theme: hyde
